### ISSUE TITLE
Login and signup needs fixing

### ISSUE THREAD

**Issue by benceisonline** [Educado-App/educado-backend#132]
## Issue Description

_The logic for checking if the user is a content creator when logging in has been removed because it breaks mobile login._

## Why do it then? 

_Mobile users should not be able to log in as creators._

## Additional Information

_Either make a new route or test with mobile before pushing. You could also save a simple boolean "isCreator" when creating a user._

- **Environment**: Backend

**Comment by Adachigaming** [comment]
What exists, or I guess existed, is all the logic Content Creators need for logging in. It was always supposed to change, and given that, I believe it seems dismissive and negligent to outright delete the logic needed for half the user base to log in.
 
I'll be more than happy to help fix it, as long as the logic we wrote remains largely the same. Write to me on Discord, and we can talk from there.

**Comment by benceisonline** [comment]
The mobile and web use the same login function. The code that was removed only allowed content creators to log in. This was clearly not intended, so it had to be removed either way.


 The issue is not logging in, but that mobile users can also log in on the web platform. We made some suggestions for relatively easy fixes under additional information.
