### ISSUE TITLE
GET user returns password

### ISSUE THREAD

**Issue by madsWesth** [Educado-App/educado-backend#201]
The get method for the `users/:id` endpoint returns the raw document from the database without the password removed. The password should **never** be sent to any client ever. The password is hashed and the route is protected by **requireLogin** middleware, which means only a client authenticated as the user they are trying to access, or a client authenticated as admin are authorized on the endpoint, so its not as bad as it could have been. It is still extremely bad practice to do this and should be fixed.

We also return the database metadata which is bad for security reasons and inefficient as the data is useless to the client(frontend) anyways.

The bigger issue at play here is that our handling of data is really poor and most endpoints return the raw database objects. We should have a system in place to more easily control what our responses from the backend looks like. This could be something like a DTO pattern or a response mapper

**Comment by Todua992** [comment]
Very simple fix, we can just do so that when we const user we exclude the password information 

`// GET User by ID
router.get('/:id', requireLogin, async (req, res) => {
	try {
		if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
			return res.status(400).send({ error: errorCodes['E0014'] });
		}
		const id = mongoose.Types.ObjectId(req.params.id);

		const user = await UserModel.findById(id).select('-password');
		console.log(user);
		return res.status(200).send(user);

	} catch (error) {
		return res.status(500).send({ error: errorCodes['E0003'] });
	}
});`
