### ISSUE TITLE
[App-Web] endpointing for reset password

### ISSUE THREAD

**Issue by MGLarsenSW** [Educado-App/educado-backend#57]
For [App] - create a new endpoint for user/reset-password
For [Web] - create a new endpoint for contentCreator/reset-password

**Comment by MortenMunk** [comment]
@MGLarsenSW PO and management is currently discussing this. If they decide, the integration team will discuss creating a single endpoint for both WEB and APP, but instead allow roles for the usermodel

**Comment by MortenMunk** [comment]
@Jatewo Is currently working on combining the endpoints
