### ISSUE TITLE
ExploreCard should only get published courses from the DB, not all. 

### ISSUE THREAD

**Issue by Donhusum** [Educado-App/educado-backend#75]
Issue Description
The current implementation of ExploreCard retrieves all courses from the database, including unpublished ones, even though the app filters and displays only the published ones. This results in unnecessary data being fetched, impacting performance and efficiency.

Steps to Reproduce
Navigate to the Explore section of the app.
Observe the data being fetched for ExploreCards.
Expected Behavior
ExploreCard should only retrieve and display published courses from the database, optimizing the app's performance and reducing unnecessary data fetching.

Actual Behavior
ExploreCard fetches all courses from the database, including unpublished ones, leading to inefficient data retrieval and potential performance issues.

Additional Information
Environment: app and backend 
Screenshots: N/A
Logs: N/A
Proposed Solution
A new route should be implemented in the backend API to specifically query the database for published courses only. This route will ensure that ExploreCard receives only the necessary data, enhancing the app's performance. Update the data fetching logic in ExploreCard component to use this new route.

**Comment by sofiiagran** [comment]
This issue is not correct. It filter the courses to check if they are published. This happens when the route is called from the app.
